#! :set filetype=yaml.docker-compose
services:
  broker:
    image: docker.io/eclipse-mosquitto:latest
    env_file: .env
    restart: on-failure
    ports:
      - ${MQTT_PORT_TCP:-1883}:${MQTT_PORT_TCP:-1883}
      - ${MQTT_PORT_WS:-9001}:${MQTT_PORT_WS:-9001}
    command:
      - /bin/sh
      - -c
      - |
        echo "listener ${MQTT_PORT_TCP:-1883}" > /mosquitto/config/mosquitto.conf
        echo "protocol mqtt" >> /mosquitto/config/mosquitto.conf
        echo "listener ${MQTT_PORT_WS:-9001}" >> /mosquitto/config/mosquitto.conf
        echo "protocol websockets" >> /mosquitto/config/mosquitto.conf
        echo "allow_anonymous false" >> /mosquitto/config/mosquitto.conf
        echo "password_file /mosquitto/config/password.txt" >> /mosquitto/config/mosquitto.conf
        echo "${MQTT_USER:-admin}:${MQTT_PASSWORD:-password}" > /mosquitto/config/password.txt
        mosquitto_passwd -U /mosquitto/config/password.txt
        mosquitto -c /mosquitto/config/mosquitto.conf

  scanner:
    image: localhost/sdr-scanner:${SDR_SCANNER_TAG:-latest}
    build:
      dockerfile: ./Dockerfile
    env_file: .env
    restart: on-failure
    depends_on:
      - broker
    volumes:
      - ./timezone:/etc/timezone:ro
      - ./localtime:/etc/localtime:ro
      - ./config/config.json:/config/config.json:rw
    devices:
      - /dev/bus/usb:/dev/bus/usb

  monitor-setup:
    image: docker.io/shajen/monitor:${MONITOR_TAG:-latest}
    env_file: .env
    restart: on-failure
    depends_on:
      - broker
    volumes:
      - ./timezone:/etc/timezone:ro
      - ./localtime:/etc/localtime:ro
      - monitor_db:/usr/src/sdr-panel/db
      - monitor_data:/usr/src/sdr-panel/public/media
    command: /entrypoint/setup.sh

  monitor-server:
    image: docker.io/shajen/monitor:${MONITOR_TAG:-latest}
    env_file: .env
    restart: on-failure
    depends_on:
      monitor-setup:
        condition: service_completed_successfully
    volumes:
      - ./timezone:/etc/timezone:ro
      - ./localtime:/etc/localtime:ro
      - monitor_db:/usr/src/sdr-panel/db
      - monitor_data:/usr/src/sdr-panel/public/media
    command: /entrypoint/server.sh
    ports:
      - ${HTTP_PORT:-8000}:8000

  monitor-worker:
    image: docker.io/shajen/monitor:${MONITOR_TAG:-latest}
    env_file: .env
    restart: on-failure
    # depends_on:
    #   monitor-setup:
    #     condition: service_completed_successfully
    volumes:
      - ./timezone:/etc/timezone:ro
      - ./localtime:/etc/localtime:ro
      - monitor_db:/usr/src/sdr-panel/db
      - monitor_data:/usr/src/sdr-panel/public/media
    command: /entrypoint/worker.sh

volumes:
  monitor_db:
  monitor_data:
